config/routes.rb
Ntranslate::Application.routes.draw do
  resources :user_projects, :only => [:index]

  resources :users do
    resources :user_projects, :only => [:edit, :update]
  end

  resources :projects do
    resources :text_resources
    member do
      get "export", :to => "exports#index"
      get "import", :to => "imports#index"
      post "import", :to => "imports#upload", :as => :import
      scope ':locale', :constraints => {:locale => /[a-z]{2}/} do
        resources :translations, :only => [:index, :create] do
          get :suggestion
        end
      end
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  get '/home', :to => "home#index", :as => :home

  root :to => "projects#index"
end

app/models/text_resource.rb
class TextResource < ActiveRecord::Base
  include TranslationMethods

  attr_accessible :key, :project_id, :content, :original_content

  belongs_to :project

  puret :content

  attr_translated :content

  validates :key, :presence => true

  validates :original_content, :presence => true

  delegate :master_language, :to => :project

  scope :pending_translation, lambda { |language|
    joins("LEFT OUTER JOIN text_resource_translations ON text_resources.id = text_resource_translations.text_resource_id AND text_resource_translations.locale = '#{language}'").
    where("translated = ? OR text_resource_translations.text_resource_id IS NULL", false)
  }

  def original_content
    content_for(master_language)
  end

  def original_content=(value)
    self.send(:"content_#{master_language}=", value)
  end

  def suggestion(language)
    text = original_content
    re = /\%\{[\w]+\}/
    matches = text.scan(re)
    matches.each_with_index do |m, i|
      text.sub!(/#{m}/, "XX#{i}XX")
    end
    text = translator.translate text, :from => master_language, :to => language
    matches.each_with_index do |m, i|
      text.sub!(/XX#{i}XX/, m)
    end
    text
  end

  after_save :expire

  # TODO: Fix this monkey path (Fork puret)
  alias_method :orig_content=, :content=

  def content=(value)
    changed_languages << I18n.locale.to_s
    self.orig_content = value
  end

  private

  def expire
    if changed_languages.include?(master_language)
      translations.select {|x| x.locale != master_language }.each do |t|
        t.update_attribute(:translated, false)
      end
    end
    changed_languages.each do |language|
      translation = translations.detect { |t| t.locale == language }
      translation.update_attribute(:translated, true)
    end
  end

  def changed_languages
    @changed_languages ||= []
  end

  def translator
    @translator ||= BingTranslator.new("ntranslate",  "Bbb+LPqrT588VVUWSdmC7WjS2pE5ix57Zjfb1vVpwTE=")
  end

end

app/controllers/text_resources_controller.rb
class TextResourcesController < ApplicationController
  before_filter :authorize
  before_filter :find_project

  # GET /text_resources
  # GET /text_resources.json
  def index
    @text_resources = @project.text_resources.
      page(params[:page]).per_page(8)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_resources }
    end
  end

  # GET /text_resources/1
  # GET /text_resources/1.json
  def show
    @text_resource = @project.text_resources.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_resource }
    end
  end

  # GET /text_resources/new
  # GET /text_resources/new.json
  def new
    @text_resource = @project.text_resources.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_resource }
    end
  end

  # GET /text_resources/1/edit
  def edit
    @text_resource = @project.text_resources.find(params[:id])
  end

  # POST /text_resources
  # POST /text_resources.json
  def create
    @text_resource = TextResource.new(:project_id => @project.id)
    @text_resource.attributes = params[:text_resource]

    respond_to do |format|
      if @text_resource.save
        format.html { redirect_to project_text_resources_path(@project), notice: 'Text resource was successfully created.' }
        format.json { render json: @text_resource, status: :created, location: @text_resource }
      else
        format.html { render action: "new" }
        format.json { render json: @text_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_resources/1
  # PUT /text_resources/1.json
  def update
    @text_resource = TextResource.find(params[:id])

    respond_to do |format|
      if @text_resource.update_attributes(params[:text_resource])
        format.html { redirect_to project_text_resources_path(@project), notice: 'Text resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_resources/1
  # DELETE /text_resources/1.json
  def destroy
    @text_resource = TextResource.find(params[:id])
    @text_resource.destroy

    respond_to do |format|
      format.html { redirect_to project_text_resources_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def authorize
    authorize! :manage, TextResource
  end

end

app/views/text_resources/_form.html.haml
= simple_form_for([@project, @text_resource]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :key, :required => true, :wrapper_html => { :class => "key" }, :hint => "i18n key of the text, e.g. rails.rumble.welcome"
    = f.input :original_content, :as => :text, :label => "Content", :required => true, :hint => "#{humanize_locale(@project.master_language)} text to translate."

  .form-actions
    = f.button :submit

app/views/text_resources/edit.html.haml
%h1 Editing text resource of project #{@project.name}

= render 'form'

app/views/text_resources/index.html.haml
.text-resources.list
  %h1.title Text resources for #{@project.name}

  = link_to "Add new text resource", new_project_text_resource_path(@project), :class => 'add btn'

  %table
    %tr
      %th
      %th
      %th

    - @text_resources.each do |text_resource|
      %tr
        %td= text_resource.key
        %td= truncate(text_resource.content_for(@project.master_language), :length => 50)
        %td= link_to image_tag("icons/pencil.png"), edit_project_text_resource_path(@project, text_resource)
        %td= link_to image_tag("icons/delete.png"), project_text_resource_path(@project, text_resource), method: :delete, data: { confirm: 'Are you sure?' }
  = will_paginate @text_resources

app/views/text_resources/new.html.haml
%h1.title New text resource for project #{@project.name}
%br
%p
  = "Create a #{humanize_locale(@project.master_language)} text resource to translate."
%br

= render 'form'

app/views/text_resources/show.html.haml
= @text_resource.key
%br
= @text_resource.content
%br
= link_to 'Edit', edit_project_text_resource_path(@project, @text_resource)
\|
= link_to 'Back', project_text_resources_path(@project)