config/routes.rb
Ntranslate::Application.routes.draw do
  resources :user_projects, :only => [:index]

  resources :users do
    resources :user_projects, :only => [:edit, :update]
  end

  resources :projects do
    resources :text_resources
    member do
      get "export", :to => "exports#index"
      get "import", :to => "imports#index"
      post "import", :to => "imports#upload", :as => :import
      scope ':locale', :constraints => {:locale => /[a-z]{2}/} do
        resources :translations, :only => [:index, :create] do
          get :suggestion
        end
      end
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  get '/home', :to => "home#index", :as => :home

  root :to => "projects#index"
end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  attr_accessible :project_id, :user_id
  belongs_to :project
  belongs_to :user
  validates :project, :user, :presence => true
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  before_filter :find_user
  before_filter :find_projects, :only => [:edit, :update]

  def index
    @user_projects = UserProject.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def edit
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def update
    @user.refresh_projects params[:projects_ids]

    respond_to do |format|
      format.html { redirect_to @user, notice: 'Projects successfully assigned.' }
    end
  end

  protected

  def find_user
    @user = User.find params[:user_id], :include => :projects
  end

  def find_projects
    @projects = Project.all
  end
end

app/views/user_projects/_form.html.haml
= form_tag(user_user_project_path(@user), :method => :put) do |f|
  .form-inputs
    %ul
      - @projects.each do |prj|
        %li
          = check_box_tag "projects_ids[]", prj.id, @user.project_ids.include?(prj.id), :id => "project_#{prj.id}"
          = label_tag "project_#{prj.id}", prj.name

  .form-actions
    = button_tag :assign

app/views/user_projects/edit.html.haml
%h1= "Assign projects to user #{@user.name}"

= render 'form'

= link_to 'Back', user_projects_path

app/views/user_projects/index.html.haml
%h1 Listing user_projects

%table
  %tr
    %th User
    %th Project
    %th
    %th
    %th

  - @user_projects.each do |user_project|
    %tr
      %td= user_project.user
      %td= user_project.project
      %td= link_to 'Show', user_project
      %td= link_to 'Edit', edit_user_project_path(user_project)
      %td= link_to 'Destroy', user_project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User project', new_user_project_path

app/views/user_projects/show.html.haml
%p
  %b User:
  = @user_project.user
%p
  %b Project:
  = @user_project.project

= link_to 'Edit', edit_user_project_path(@user_project)
\|
= link_to 'Back', user_projects_path