config/routes.rb
Ntranslate::Application.routes.draw do
  resources :user_projects, :only => [:index]

  resources :users do
    resources :user_projects, :only => [:edit, :update]
  end

  resources :projects do
    resources :text_resources
    member do
      get "export", :to => "exports#index"
      get "import", :to => "imports#index"
      post "import", :to => "imports#upload", :as => :import
      scope ':locale', :constraints => {:locale => /[a-z]{2}/} do
        resources :translations, :only => [:index, :create] do
          get :suggestion
        end
      end
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  get '/home', :to => "home#index", :as => :home

  root :to => "projects#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :languages, :master_language

  has_many :text_resources
  has_many :user_projects, :dependent => :destroy
  has_many :users, :through => :user_projects

  serialize :languages

  validates :name, :presence => true, :format => { :with => /\A[a-zA-Z0-9\-_]+\z/, :message => "Only letters, numbers, - and _ are allowed" }
  validates :languages, :master_language, :presence => true
  validate :languages_contain_master_language

  before_save :clean_languages

  def text_resources_count
    text_resources.count
  end

  def has_pending_translations?(locale)
    pending_translations_count(locale) > 0
  end

  def pending_translations_count(locale)
    locale == master_language ? 0 : text_resources.pending_translation(locale).count
  end

  def languages_without_master
    languages - [master_language]
  end

  def to_param
    "#{id}-#{name.downcase}"
  end

  def languages_records
    Language.where("iso_code in (?)", languages)
  end

private

  def clean_languages
    languages.delete_if(&:blank?)
  end

  def languages_contain_master_language
    if languages.exclude? master_language
      errors.add(:master_language, "Should be one of the languages")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  set_tab :home, :except => %w(show edit)

  before_filter :authorize, :except => [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.page(params[:page]).per_page(4).
      all(:include => :text_resources)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id], :include => :text_resources)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy

    flash[:error] = "Nice try. We've disabled project deletion until the rumble is over. ;-)"
    redirect_to projects_url and return

    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

private

  def authorize
    authorize! :manage, Project
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def link_to_translate(project, language)
    link = link_to "translate!", translations_path(project, language)
    resources_text = pluralize(project.pending_translations_count(language), "text resource")

    "#{humanize_locale(language)}: #{resources_text} to #{link}".html_safe
  end

  def random_logo(project, options = {})
    size = if options[:size] == :big
             "400/200"
           else
             "200/100"
           end

    image_id = project.id % 10
    image_tag "http://lorempixel.com/#{size}/nature/#{image_id}/LOGO"
  end

end

app/views/projects/_form.html.haml
= simple_form_for(@project, :html => {:class => 'project create'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :wrapper_html => {:class => 'name'}, :hint  => 'Please choose a nice short name for your project. Only letters, numbers, - and _ are allowed.'
    = f.input :master_language, :collection => languages_collection, :as => :select, :selected => @project.master_language, :include_blank => @project.new_record?, :hint  => 'Original language of your text resources. Should be one of the languages below.'
    = f.input :languages, :collection => languages_collection, :as => :check_boxes, :hint  => 'These are the languages you would like to have your text resources translated to.'

  .form-actions
    = f.button :submit

:javascript
  $('#project_master_language').change(function() {
    var l = $("#project_master_language option:selected").val();
    var chk = $('#project_languages_' + l);
    chk.attr('checked', 'checked');
  });

app/views/projects/_language.html.haml
.language-stats
  - if language == project.master_language
    = "#{project.text_resources_count} text resources in total"
  - else
    - if project.has_pending_translations?(language)
      = link_to_translate(project, language)
    - else
      = "#{humanize_locale(language)}: Nothing to translate"

app/views/projects/_language_statistics.html.haml
- if project.text_resources.count == 0
  Nothing to translate
- else
  = render "language", :project => project, :language => project.master_language

  - for language in project.languages_without_master
    = render :partial => "language", :locals => { :project => project, :language => language }

app/views/projects/_project.html.haml
.name
  .links
    = link_to project.name, project, :class => "title"
    - if can? :manage, Project
      = link_to image_tag("icons/pencil.png", :title => "Edit"), edit_project_path(project)

  .image
    = link_to project do
      = random_logo(project)

= render "language_statistics", :project => project

app/views/projects/edit.html.haml
%h1= "Editing project #{@project.name}"

= render 'form'

app/views/projects/index.html.haml
.project.list
  - @projects.in_groups_of(2, false) do |projects|
    .row
      - projects.each do |project|
        .translation-project
          = render "project", :project => project

  - if can? :manage, Project
    .actions
      = link_to 'New Project', new_project_path, :class => 'btn'

  %br
  %br
  = will_paginate @projects

app/views/projects/new.html.haml
%h1 New project

= render 'form'

app/views/projects/show.html.haml
%h1.title
  = @project.name

.project-block.info
  = random_logo(@project, :size => :big)

  .project-translation-stats
    = render "language_statistics", :project => @project

- if can? :manage, Project
  .project-block.manage
    %h4
      Manage your project
    %ul
      %li
        = link_to edit_project_path(@project) do
          Edit #{image_tag("icons/pencil.png", :title => "Edit")}
      %li
        = link_to(@project, method: :delete, data: { confirm: 'Are you sure?' }) do
          Delete #{image_tag("icons/delete.png", :title => "Delete")}
      %li
        = link_to new_project_text_resource_path(@project) do
          Add new text resource #{image_tag("icons/add.png", :title => "Add")}
      %li
        = link_to import_project_path(@project) do
          Bulk import text resources #{image_tag("icons/page_white_get.png", :title => "Import")}
      %li
        = link_to export_project_path(@project, :format => 'yaml') do
          Export as YAML #{image_tag("icons/page_white_ruby.png", :title => "Export as YAML")}
      %li
        = link_to export_project_path(@project, :format => 'json') do
          Export as JSON #{image_tag("icons/page_white_put.png", :title => "Export as JSON")}