config/routes.rb
Ntranslate::Application.routes.draw do
  resources :user_projects, :only => [:index]

  resources :users do
    resources :user_projects, :only => [:edit, :update]
  end

  resources :projects do
    resources :text_resources
    member do
      get "export", :to => "exports#index"
      get "import", :to => "imports#index"
      post "import", :to => "imports#upload", :as => :import
      scope ':locale', :constraints => {:locale => /[a-z]{2}/} do
        resources :translations, :only => [:index, :create] do
          get :suggestion
        end
      end
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  get '/home', :to => "home#index", :as => :home

  root :to => "projects#index"
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= tabs_tag(:builder => MenuTabBuilder) do |tab|

  = tab.home "Projects", root_path

  - if @project && @project.persisted?
    = tab.projects @project.name, project_path(@project)

    - if can?(:manage, TextResource)
      = tab.text_resources "Text Resources", project_text_resources_path(@project)

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Ntranslate"
      %meta{:content => content_for?(:description) ? yield(:description) : "Ntranslate", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Euphoria+Script"
        = javascript_include_tag "application"
        = javascript_include_tag "/js/easySlider1.5.js"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .main
      .click.login-wrapper
        .login
          - if signed_in?
            = welcome_user
            %span.auth_provider
              = link_to "Sign out", signout_path
          - else
            %a{:href => "/auth/github", :class => "auth_provider"}
              Sign in with Github
            = image_tag "github_32.png", :size => "32x32", :alt => "Github"
            %a{:href => "/auth/twitter", :class => "auth_provider"}
              Sign in with Twitter
            = image_tag "twitter_32.png", :size => "32x32", :alt => "Twitter"

      .header-wrapper
        .header
          .logo
            %a{:href => root_url}
              ntranslate

          - if signed_in?
            .menu
              = render 'layouts/navigation'

      .body-wrapper
        .body
          .content
            = render 'layouts/messages'
            = yield
    .footer
      .footer_resize
        =link_to "http://railsrumble.com/" do
          = image_tag("rr-logo.png")

        %p.leftt
          ntranslate. Barceloners 2012. All Rights Reserved.
          %a{:href => "mailto:ntranslate.app@gmail.com"}
            contact us
        .clr
      .clr

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35578841-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();